services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Simpleevents\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  B13\Simpleevents\Hooks\DataHandlerCacheHook:
    public: true
    arguments:
      $cachePages: '@cache.pages'
